site_name: ğŸŒŒP.A.R.A System
site_url: https://funny-han.github.io

nav:
  - ğŸ  HOME ä¸»é¡µ: index.md
  - ğŸŒ² Resrouce èµ„æº:
    - ğŸ’» è®¡ç®—åŸºç¡€:
      - ğŸ•¸ Web å¼€å‘:
        - ğŸ“• Django æ–°æ‰‹å…¥é—¨:
          - ğŸ“ƒ Chapter 0 Introduction: RESOURCES\computer_science\django_by_example\chapter_00_introduction.md
          - ğŸ“ƒ Chapter 1 Initial Set Up: RESOURCES\computer_science\django_by_example\chapter_01_initial_set_up.md
theme:
  name: material
  features:
    - navigation.tabs  # å¯ç”¨é¡¶éƒ¨æ ‡ç­¾å¼å¯¼èˆª
    - navigation.indexes  # å¯é€‰ï¼šæ˜¾ç¤ºç´¢å¼•é¡µé¢

markdown_extensions:
  - footnotes # å¼€å¯ md è„šæ³¨

