site_name: ğŸŒŒP.A.R.A System
site_url: https://funny-han.github.io

nav:
  - ğŸ HOME: index.md
  - Computer Science è®¡ç®—åŸºç¡€:
    - Web å¼€å‘:
      - Django for Beginners ä¸­æ–‡ç¿»è¯‘:
        - Chapter 0 Introduction: RESOURCES\computer_science\django_by_example\chapter_00_introduction.md
        - Chapter 1 Initial Set Up: RESOURCES\computer_science\django_by_example\chapter_01_initial_set_up.md
theme:
  name: simple-blog

markdown_extensions:
  - footnotes
